name: GPT5 Query

on:
  repository_dispatch:
    types: [gpt5_query]

jobs:
  run_gpt5:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Python installieren
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Abhängigkeiten installieren
      - name: Install dependencies
        run: pip install requests

      # 4️⃣ GPT-5 / Claude / Gemini Antwort generieren
      - name: Generate GPT-5 response
        env:
          GPT5_API_KEY: ${{ secrets.GPT5_API_KEY }}
        run: |
          python - <<EOF
import os
import requests

prompt = "${{ github.event.client_payload.prompt }}"
api_key = os.getenv("GPT5_API_KEY")

# ⬅️ HIER ECHTE KI-API-URL EINSETZEN
url = "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"  

# ⬅️ HIER HEADERS ANPASSEN, Z.B. für Claude / Gemini / GPT-5
headers = {
    "Authorization": f"Bearer {api_key}",
    "Content-Type": "application/json"
}

# ⬅️ HIER DATEN ANPASSEN, je nach API-Spezifikation
data = {
    "prompt": prompt,
    "max_tokens": 300
}

response = requests.post(url, json=data, headers=headers)

# ⬅️ HIER ANPASSEN, wie die Antwort aus der API extrahiert wird
answer = response.json().get("text", "Keine Antwort erhalten.")

# Antwort in response.txt schreiben
with open("response.txt", "w") as f:
    f.write(answer)
EOF

      # 5️⃣ Commit & Push response.txt
      - name: Commit response
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add response.txt
          git commit -m "GPT-5 Antwort generiert"
          git push
