name: GPT5 Query

on:
  repository_dispatch:
    types: [gpt5_query]

jobs:
  run_gpt5:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Python installieren
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Abhängigkeiten installieren
      - name: Install dependencies
        run: pip install requests

      # 4️⃣ GPT-5 / Claude / Gemini Antwort generieren
      - name: Generate GPT-5 response
        env:
          GPT5_API_KEY: ${{ secrets.GPT5_API_KEY }}   # ⬅️ Dein KI-API-Key
        run: |
          python - <<EOF
import os
import requests

prompt = "${{ github.event.client_payload.prompt }}"
api_key = os.getenv("GPT5_API_KEY")

# ⬅️ HIER DEINE KI-API URL EINSETZEN
# Beispiel: Claude → "https://api.anthropic.com/v1/complete"
# Beispiel: GPT-5 → "https://api.gpt5.example.com/v1/generate"
url = "https://api.openai.com/v1/chat/completions"

headers = {
    "Authorization": f"Bearer {api_key}",
    "Content-Type": "application/json"
}

data = {
    "prompt": prompt,
    "max_tokens": 300
}

try:
    response = requests.post(url, json=data, headers=headers, timeout=30)
    response.raise_for_status()
    answer = response.json().get("text", "Keine Antwort erhalten.")
except Exception as e:
    answer = f"❌ Fehler bei KI-API: {e}"

# Antwort in response.txt schreiben
with open("response.txt", "w", encoding="utf-8") as f:
    f.write(answer)
EOF

      # 5️⃣ Commit & Push response.txt
      - name: Commit & push response
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}  # ⬅️ Dein GitHub-PAT
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_PAT}@github.com/${{ github.repository }}.git
          git add response.txt
          git commit -m "GPT-5 Antwort generiert" || echo "Keine Änderungen zum Committen"
          git push
