name: GPT5 Query

on:
  repository_dispatch:
    types: [gpt5_query]

jobs:
  run_gpt5:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Python installieren
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Abhängigkeiten installieren
      - name: Install dependencies
        run: pip install azure-ai-inference

      # 4️⃣ GPT-5 Antwort generieren via GitHub Models
      - name: Generate GPT-5 response
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}  # Dein GitHub Personal Access Token
        run: |
          python - <<EOF
import os
from azure.ai.inference import ChatCompletionsClient
from azure.ai.inference.models import SystemMessage, UserMessage
from azure.core.credentials import AzureKeyCredential

# Prompt vom repository_dispatch Event
prompt = "${{ github.event.client_payload.prompt }}"

# GitHub Models Endpoint
endpoint = "https://models.github.ai/inference"
model = "openai/gpt-5"

# Authentifizierung mit PAT
token = os.environ["GITHUB_PAT"]
client = ChatCompletionsClient(endpoint=endpoint, credential=AzureKeyCredential(token))

try:
    response = client.complete(
        messages=[
            SystemMessage("You are a helpful assistant."),
            UserMessage(prompt)
        ],
        model=model
    )
    answer = response.choices[0].message.content
except Exception as e:
    answer = f"❌ Fehler bei GitHub Model API: {e}"

# Antwort in response.txt schreiben
with open("response.txt", "w", encoding="utf-8") as f:
    f.write(answer)
EOF

      # 5️⃣ Commit & Push response.txt zurück ins Repo
      - name: Commit & push response
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_PAT}@github.com/${{ github.repository }}.git
          git add response.txt
          git commit -m "GPT-5 Antwort generiert" || echo "Keine Änderungen zum Committen"
          git push
