name: GPT5 Query

on:
  repository_dispatch:
    types: [gpt5_query]

jobs:
  run_gpt5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Generate GPT-5 response
        env:
          GPT5_API_KEY: ${{ secrets.GPT5_API_KEY }}
        run: |
          touch response.txt
          python - <<EOF
import os
import requests

prompt = "${{ github.event.client_payload.prompt }}"
api_key = os.getenv("GPT5_API_KEY")

# ERSETZE durch deine echte GPT-5 API URL
url = "https://api.gpt5.example.com/v1/generate"
headers = {"Authorization": f"Bearer {api_key}"}
data = {"prompt": prompt, "max_tokens": 200}

response = requests.post(url, json=data, headers=headers)
answer = response.json().get("text", "Keine Antwort erhalten.")

with open("response.txt", "w") as f:
    f.write(answer)
EOF

      - name: Commit response
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add response.txt
          git commit -m "GPT-5 Antwort generiert" || echo "Keine Änderungen"
          git push
